# --------------------------------------------------------------
# Choose bag name
# --------------------------------------------------------------
bag_name: 

# --------------------------------------------------------------
# Path section to download
# --------------------------------------------------------------
part_nr: 1

# --------------------------------------------------------------
# Data to record
# --------------------------------------------------------------
save_images: True
save_imu: False
save_gt: False